services:
  xatabchik:
    build: .
    restart: unless-stopped
    ports:
      - target: 1488
        published: 1488
        host_ip: "127.0.0.1"
        protocol: tcp
    volumes:
      - .:/app/project
    environment:
      TELEGRAM_PROXY: ${TELEGRAM_PROXY:-}
      SHOPBOT_FLASK_HOST: "0.0.0.0"
      TICKET_FILES_DIR: /app/project/ticket_files
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: xatabchik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  xatabchik-webapp:
    build: .
    restart: unless-stopped
    command: /app/.venv/bin/uvicorn shop_bot.webapp.handlers:app --host 0.0.0.0 --port 8000 --proxy-headers
    ports:
      - 127.0.0.1:8001:8000
    volumes:
      - .:/app/project
    environment:
      TELEGRAM_PROXY: ${TELEGRAM_PROXY:-}
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: xatabchik-webapp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"